# render.yaml

databases:
  - name: pft-db
    plan: pro
    databaseName: app
    user: app

services:
  - type: web
    name: pft-api
    env: docker
    rootDir: 7project/personal-finance-tracker/backend
    plan: pro
    healthCheckPath: /api/healthz
    envVars:
      - key: PORT
        value: 8080
      - key: JWT_SECRET
        generateValue: true
      - key: DB_DSN
        fromDatabase:
          name: pft-db
          property: connectionString

  - type: web
    name: pft-frontend
    env: docker
    rootDir: 7project/personal-finance-tracker/frontend
    plan: pro
    envVars:
      - key: VITE_API_BASE
        value: /api
